### ISSUE TITLE
Add a date-field to Batterynotes in order to document when full battery provided/replace for the device

### ISSUE THREAD

**Issue by Alfred99-HA** [andrew-codechimp/HA-Battery-Notes#103] opened 2023-12-19 14:51 UTC
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Actually I am quite happy with battery notes since I use it. It will even become more useful as I add more devices

### Describe the solution you'd like

Having date of preoviding new full battery alltogether with the type of the battery and the device will help understand how long a battery for a device lasted and/or prognose whow long it will last before need to replace it.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by andrew-codechimp** [comment] 2023-12-19 15:15
Duplicate of https://github.com/andrew-codechimp/HA-Battery-Notes/issues/23

**Closed by andrew-codechimp** 2023-12-19 15:15 UTC
